version: '3'
services:
  hadoop:
    image: "weli/hadoop-learn"
    ports:
      - "2122:2122" # sshd
      - "5900:5900" # vnc
      - "8088:8088" # yarn/resource manager
      - "8042:8042" # yarn/node manager port
      - "9000:9000" # hdfs/namenode port
      - "19888:19888" # yarn/job history server
  oozie:
    image: "weli/hadoop-oozie"
    ports:
      - "11000:11000" # oozie admin port
    depends_on:
      - "hadoop"
